name: PRLF
favicon: null
layout_spectrum: 0.4665414036717266
typography_spectrum: 0.2476256601512432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8835700668860227
  lightness: 0.36422066227532923
  saturation: 0.4929014111403376
  rhythmicContrast: 0.669639646075666
purpose: []
