name: PRLF
favicon: null
layout_spectrum: 0.95372
typography_spectrum: 0.56383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c4aa0'
    - '#b0c4ed'
    - '#99071f'
    - '#000080'
  brandStrength: 0.8835700668860227
  lightness: 0.36422066227532923
  saturation: 0.4929014111403376
  rhythmicContrast: 0.669639646075666
purpose: []
